---
- name: Setup WebServer
  hosts: webservergrp
  become: yes  
  tasks:
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present
    - name: Start and Enabling HTTPD
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Uploading File to server
      copy:
        src: index.html
        dest: /var/www/html/index.html




- name: Setup DBserver
  hosts: dbservergrp
  become: yes
  tasks:
    - name: Install Mysql Server
      yum:
        name: mariadb-server
        state: present
    - name: Start and Enabling DB
      service:
        name: mariadb-server
        state: started
        enabled: yes

